
server:
  port: 8770

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/demoklis/springCloudConfig/
          searchPaths: respo
      label: master
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/