eureka:
#  instance:
#    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://peer1:8761/eureka/
#    registryFetchIntervalSeconds: 10
server:
  port: 8762

spring:
  application:
    name: service-hi
#  zipkin:
#    base-url: http://localhost:8773