spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: service-hi
  application:
    name: service-hi
server:
  port: 8503
endpoints:
  health:
    sensitive : false
management:
  security:
    enabled: false
    